name: Docker Image CI

on:
  push:
    branches: [master, release]

jobs:
  build-deploy-image:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: radix-job-scheduler
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}-latest
          docker build -t radixdev.azurecr.io/$IMAGE_NAME:$IMAGE_TAG -t radixprod.azurecr.io/$IMAGE_NAME:$IMAGE_TAG .
      - uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Push to radixdev
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}-latest
          az acr login -n radixdev -g common
          docker push radixdev.azurecr.io/$IMAGE_NAME:$IMAGE_TAG
          az logout
      - uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}
      - name: Push to radixprod
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}-latest
          az acr login -n radixprod -g common
          docker push radixprod.azurecr.io/$IMAGE_NAME:$IMAGE_TAG