name: radix-job-scheduler-pr
on:
  pull_request:
    branches:
    - main
    - update-refs
jobs:
  build:
    name: pull-request-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        platforms: |
          linux/amd64
          linux/arm64

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Install dependencies
      run: go mod download
    - name: Run Tests
      run: go test -cover `go list ./...`

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.58.2

  verify-code-generation:
    name: Verify Code Generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Verify Code Generation
        run: |
          make verify-generate

  report-swagger-changes:
    name: Report Changes In Swagger Spec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Install Swagger
        run: go install github.com/go-swagger/go-swagger/cmd/swagger@v0.31.0
      - name: Check breaking changes
        if: always()
        id: breaking
        continue-on-error: true
        run: breaking_changes=$(swagger diff --break <(git show main:swaggerui/html/swagger.json) swaggerui/html/swagger.json) >> $GITHUB_OUTPUT
      - name: Add comment
#        if: failure() && steps.breaking.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: console.log('${{ steps.breaking.outputs.breaking_changes }}');
