name: radix-job-scheduler-pr
on:
  pull_request:
    branches:
    - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      env:
        REF: ${{ github. sha }}
      run: docker build -t radix-job-scheduler:${REF##*/} .

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go mod download
      - name: Install GolangCI Lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2

      - name: golangci-lint
        run: golangci-lint run --timeout=30m --max-same-issues=0 --out-format=github-actions

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go mod download
      - name: Run Tests
        run: go test -cover `go list ./... | grep -v 'pkg/client'`

  test-swagger:
    name: Test Swagger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go mod download
      - name: Install Swagger
        run: go install github.com/go-swagger/go-swagger/cmd/swagger@v0.30.5
      - name: Generate Swagger
        run: swagger generate spec -o ./swagger.json --scan-models --exclude-deps
      - name: Validate no changes
        run: diff swagger.json ./swaggerui/html/swagger.json
      - name: Check breaking changes
        if: always()
        id: breaking
        continue-on-error: true
        run: swagger diff --break <(git show master:swaggerui/html/swagger.json) swagger.json > /tmp/swagger_breaking_changes.txt
      - name: Add comment
        if: failure() && steps.breaking.outcome == 'failure'
        uses: mshick/add-pr-comment@v2
        with:
          message-id: breaking-comment
          preformatted: true
          message-path: /tmp/swagger_breaking_changes.txt
